// local exports
export 'package:flutter/material.dart';
export 'package:provider/provider.dart';
export 'package:font_awesome_flutter/font_awesome_flutter.dart';
export 'dart:io';
export 'package:image_cropper/image_cropper.dart';
export 'package:image_picker/image_picker.dart';
// utils
export 'package:finapp/routes/routes_name.dart';
export 'package:finapp/viewModel/login_provider.dart';
export 'package:finapp/viewModel/register_provider.dart';
export 'package:finapp/viewModel/bottom_navbar.dart';
export 'package:finapp/model/product_icon_model.dart';
export 'package:finapp/model/home_button_model.dart';
export 'package:finapp/model/vehicles_model.dart';
export 'package:finapp/viewModel/image_picker.dart';

// screen
export 'package:finapp/main.dart';
// manager
export 'package:finapp/screen/managerScreen/addRemoveSalesExe/detail_salesexe_screen.dart';
export 'package:finapp/screen/managerScreen/addRemoveSalesExe/list_salesexe_screen.dart';
export 'package:finapp/screen/managerScreen/manageLoan/applied_user_list_screen.dart';
export 'package:finapp/screen/managerScreen/manageLoan/approve_reject_screen.dart';
export 'package:finapp/screen/managerScreen/manager_home_page.dart';
export 'package:finapp/screen/managerScreen/profile/manager_profile_screen.dart';
export 'package:finapp/screen/managerScreen/profile/manager_edit_profile_screen.dart';
export 'package:finapp/screen/managerScreen/user/remove_restrict_user.dart';
// admin
export 'package:finapp/screen/adminScreen/home/dashboard_screen.dart';
export 'package:finapp/screen/adminScreen/loanapprove/loan_approve_screen.dart';
export 'package:finapp/screen/adminScreen/manageusers/manager/manage_manager_screen.dart';
export 'package:finapp/screen/adminScreen/manageusers/manager/remove_restrict_manager.dart';
export 'package:finapp/screen/adminScreen/manageusers/salesexecutive/admin_add_salesexe.dart';
export 'package:finapp/screen/adminScreen/manageusers/salesexecutive/remove_restrict_selesexe.dart';
export 'package:finapp/screen/adminScreen/manageusers/manager/admin_add_manager.dart';
export 'package:finapp/screen/adminScreen/manageusers/salesexecutive/manage_selesexe_screen.dart';
export 'package:finapp/screen/adminScreen/profile/admin_profile_screen.dart';
export 'package:finapp/screen/adminScreen/manageusers/user/manage_user_screen.dart';
export 'package:finapp/screen/adminScreen/admin_home_screen.dart';
export 'package:finapp/screen/adminScreen/manageusers/user/admin_add_user.dart';
export 'package:finapp/screen/adminScreen/loanapprove/loan_details_screen.dart';
export 'package:finapp/screen/adminScreen/loanapprove/one_user_loan_screen.dart';
export 'package:finapp/screen/adminScreen/manageusers/user/remove_restrict_user.dart';
export 'package:finapp/screen/adminScreen/profile/admin_edit_profile.dart';
// user
export 'package:finapp/screen/userScreen/Login/login_screen.dart';
export 'package:finapp/screen/userScreen/OTP/get_started_page.dart';
export 'package:finapp/screen/userScreen/Register/register_screen.dart';
export 'package:finapp/screen/userScreen/Home/all_product.dart';
export 'package:finapp/screen/userScreen/Offer/offer_screen.dart';
export 'package:finapp/screen/userScreen/Rewards/rewards_screen.dart';
export 'package:finapp/screen/userScreen/Account/account_page.dart';
export 'package:finapp/screen/userScreen/Home/home_screen.dart';
export 'package:finapp/screen/userScreen/Home/home.dart';
export 'package:finapp/screen/userScreen/AllRelations/relation_details.dart';
export 'package:finapp/screen/userScreen/AllRelations/relation_page.dart';
export 'package:finapp/screen/userScreen/BillAndRecharge/bill_option_page.dart';
export 'package:finapp/screen/userScreen/BillAndRecharge/bill_recharge_page.dart';
export 'package:finapp/screen/userScreen/BillAndRecharge/recharge_search_page.dart';
export 'package:finapp/screen/userScreen/DigitalCard/digital_card_page.dart';
export 'package:finapp/screen/userScreen/UpiPage/upi_page.dart';
export 'package:finapp/screen/userScreen/UpiPage/upi_search_page.dart';
export 'package:finapp/screen/userScreen/Account/account_edit_page.dart';
export 'package:finapp/screen/userScreen/Home/electronic_product.dart';
export 'package:finapp/screen/userScreen/Home/insurance/general_insurance.dart';
export 'package:finapp/screen/userScreen/Home/insurance/insurance_screen.dart';
export 'package:finapp/screen/userScreen/Home/lifestyle_screen.dart';
export 'package:finapp/screen/userScreen/Home/vehicles_scrren.dart';
// sales executive
export 'package:finapp/screen/salesExecutiveScreen/loanScreens/bike_loan_screen.dart';
export 'package:finapp/screen/salesExecutiveScreen/loanScreens/car_loan_screen.dart';
export 'package:finapp/screen/salesExecutiveScreen/loanScreens/gold_loan_screen.dart';
export 'package:finapp/screen/salesExecutiveScreen/loanScreens/prorerty_loan_screen.dart';
export 'package:finapp/screen/salesExecutiveScreen/dashboard/loanApprovel/loan_approvel_details.dart';
export 'package:finapp/screen/salesExecutiveScreen/dashboard/loanPanding/loan_panding_details.dart';
export 'package:finapp/screen/salesExecutiveScreen/dashboard/loanRejection/loan_rejection_details.dart';
export 'package:finapp/screen/salesExecutiveScreen/profile/sales_executive_profile_edit.dart';
export 'package:finapp/screen/salesExecutiveScreen/sales_executive_home_screen.dart';

// widget
export 'package:finapp/widget/text_filds.dart';
export 'package:finapp/widget/asset_image.dart';
export 'package:finapp/widget/text_button.dart';
export 'package:finapp/widget/elevated_button.dart';
export 'package:finapp/widget/text_widget.dart';
export 'package:finapp/widget/post_card.dart';
export 'package:finapp/widget/top_button.dart';
export 'package:finapp/widget/emi_show_container.dart';    
export 'package:finapp/widget/text_number_row.dart';    
export 'package:finapp/widget/loding_page.dart';
// constant
export 'package:finapp/constant/colors.dart';
export 'package:finapp/constant/homeicons.dart';
export 'package:finapp/constant/rewards.dart';
export 'package:finapp/constant/products.dart';
export 'package:finapp/constant/offers.dart';
export 'package:finapp/constant/rating.dart';
export 'package:finapp/constant/vehicles.dart';
export 'package:finapp/constant/dashboard.dart';

