// local exports
export 'package:flutter/material.dart';
export 'package:provider/provider.dart';
export 'package:font_awesome_flutter/font_awesome_flutter.dart';
// utils
export 'package:finapp/routes/routes_name.dart';
export 'package:finapp/viewModel/login_provider.dart';
export 'package:finapp/viewModel/register_provider.dart';
export 'viewModel/bottom_navbar.dart';
export 'package:finapp/model/product_icon.dart';
export '../model/home_button.dart';

// screen
export 'package:finapp/screen/Login/login_screen.dart';
export '../screen/OTP/get_started_page.dart';
export '../screen/Register/register_screen.dart';
export 'package:finapp/screen/Home/all_product.dart';
export 'package:finapp/screen/Offer/offer_screen.dart';
export 'package:finapp/screen/Rewards/rewards_screen.dart';
export 'package:finapp/screen/Account/account_page.dart';
export 'package:finapp/screen/Home/home_screen.dart';
export 'package:finapp/screen/Scan/scan_screen.dart';
export 'package:finapp/screen/Home/home.dart';
export 'package:finapp/screen/AllRelations/relation_details.dart';
export 'package:finapp/screen/AllRelations/relation_page.dart';
export 'package:finapp/screen/BillAndRecharge/bill_option_page.dart';
export 'package:finapp/screen/BillAndRecharge/bill_recharge_page.dart';
export 'package:finapp/screen/BillAndRecharge/recharge_search_page.dart';
export 'package:finapp/screen/DigitalCard/digital_card_page.dart';
export 'package:finapp/screen/UpiPage/upi_page.dart';
export 'package:finapp/screen/UpiPage/upi_search_page.dart';

// widget
export 'package:finapp/widget/text_filds.dart';
export 'package:finapp/widget/asset_image.dart';
export 'package:finapp/widget/text_button.dart';
export 'package:finapp/widget/elevated_button.dart';
export 'package:finapp/widget/text_widget.dart';
export 'package:finapp/widget/post_card.dart';
export 'package:finapp/widget/top_button.dart';
export 'package:finapp/widget/emi_show_container.dart';      
export 'package:finapp/screen/Account/account_edit_page.dart';
export 'package:finapp/screen/Home/electronic_product.dart';
export 'package:finapp/screen/Home/insurance/general_insurance.dart';
export 'package:finapp/screen/Home/insurance/insurance_screen.dart';
export 'package:finapp/screen/Home/lifestyle_screen.dart';
export 'package:finapp/screen/Home/vehicles_scrren.dart';

// constant
export 'package:finapp/constant/colors.dart';
export 'package:finapp/constant/homeicons.dart';
export 'package:finapp/constant/rewards.dart';
export 'package:finapp/constant/products.dart';
export 'package:finapp/constant/offers.dart';
