// local exports
export 'package:flutter/material.dart';
export 'package:provider/provider.dart';
export 'package:font_awesome_flutter/font_awesome_flutter.dart';
// utils
export 'package:finapp/routes/routes_name.dart';
export 'package:finapp/viewModel/login_provider.dart';
export 'package:finapp/viewModel/register_provider.dart';
export 'package:finapp/viewModel/bottom_navbar.dart';
export 'package:finapp/model/product_icon_model.dart';
export 'package:finapp/model/home_button_model.dart';
export 'package:finapp/model/vehicles_model.dart';

// screen
export 'package:finapp/main.dart';
export 'package:finapp/screen/adminScreen/home/dashboard_screen.dart';
export 'package:finapp/screen/adminScreen/loanapprove/loan_approve_screen.dart';
export 'package:finapp/screen/adminScreen/manageusers/manager/manage_manager_screen.dart';
export 'package:finapp/screen/adminScreen/manageusers/manager/remove_restrict_manager.dart';
export 'package:finapp/screen/adminScreen/manageusers/salesexecutive/admin_add_salesexe.dart';
export 'package:finapp/screen/adminScreen/manageusers/salesexecutive/remove_restrict_selesexe.dart';
export 'package:finapp/screen/adminScreen/manageusers/manager/admin_add_manager.dart';
export 'package:finapp/screen/adminScreen/manageusers/salesexecutive/manage_selesexe_screen.dart';
export 'package:finapp/screen/adminScreen/profile/admin_profile_screen.dart';
export 'package:finapp/screen/adminScreen/manageusers/user/manage_user_screen.dart';
export 'package:finapp/screen/adminScreen/admin_home_screen.dart';
export 'package:finapp/screen/adminScreen/manageusers/user/admin_add_user.dart';
export 'package:finapp/screen/adminScreen/manageusers/user/remove_restrict_user.dart';
export 'package:finapp/screen/adminScreen/profile/admin_edit_profile.dart';
export 'package:finapp/screen/userScreen/Login/login_screen.dart';
export 'package:finapp/screen/userScreen/OTP/get_started_page.dart';
export 'package:finapp/screen/userScreen/Register/register_screen.dart';
export 'package:finapp/screen/userScreen/Home/all_product.dart';
export 'package:finapp/screen/userScreen/Offer/offer_screen.dart';
export 'package:finapp/screen/userScreen/Rewards/rewards_screen.dart';
export 'package:finapp/screen/userScreen/Account/account_page.dart';
export 'package:finapp/screen/userScreen/Home/home_screen.dart';
export 'package:finapp/screen/userScreen/Home/home.dart';
export 'package:finapp/screen/userScreen/AllRelations/relation_details.dart';
export 'package:finapp/screen/userScreen/AllRelations/relation_page.dart';
export 'package:finapp/screen/userScreen/BillAndRecharge/bill_option_page.dart';
export 'package:finapp/screen/userScreen/BillAndRecharge/bill_recharge_page.dart';
export 'package:finapp/screen/userScreen/BillAndRecharge/recharge_search_page.dart';
export 'package:finapp/screen/userScreen/DigitalCard/digital_card_page.dart';
export 'package:finapp/screen/userScreen/UpiPage/upi_page.dart';
export 'package:finapp/screen/userScreen/UpiPage/upi_search_page.dart';
export 'package:finapp/screen/userScreen/Account/account_edit_page.dart';
export 'package:finapp/screen/userScreen/Home/electronic_product.dart';
export 'package:finapp/screen/userScreen/Home/insurance/general_insurance.dart';
export 'package:finapp/screen/userScreen/Home/insurance/insurance_screen.dart';
export 'package:finapp/screen/userScreen/Home/lifestyle_screen.dart';
export 'package:finapp/screen/userScreen/Home/vehicles_scrren.dart';

// widget
export 'package:finapp/widget/text_filds.dart';
export 'package:finapp/widget/asset_image.dart';
export 'package:finapp/widget/text_button.dart';
export 'package:finapp/widget/elevated_button.dart';
export 'package:finapp/widget/text_widget.dart';
export 'package:finapp/widget/post_card.dart';
export 'package:finapp/widget/top_button.dart';
export 'package:finapp/widget/emi_show_container.dart';    
export 'package:finapp/widget/text_number_row.dart';    

// constant
export 'package:finapp/constant/colors.dart';
export 'package:finapp/constant/homeicons.dart';
export 'package:finapp/constant/rewards.dart';
export 'package:finapp/constant/products.dart';
export 'package:finapp/constant/offers.dart';
export 'package:finapp/constant/rating.dart';
export 'package:finapp/constant/vehicles.dart';

